stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  DOCKER_APP_TAG: v1

build:
  stage: build
  image: docker:dind
  services:
    - name: docker:dind
  only:
    - dev
  before_script:
    - echo "Docker registry Login"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "Docker image building"
    - docker build -f Dockerfile.build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
    - docker tag $DOCKER_IMAGE_TAG $CI_REGISTRY_IMAGE:$DOCKER_APP_TAG
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_APP_TAG 

deploy_staging:
  stage: deploy
  tags:
    - unicef-lprs-front
  only:
    - dev
  before_script:
    - echo "Docker registry Login"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Setting env vars"
    - cp .env.example deploy/.env
    - sed -i '/^REACT_APP_API_BASE_URL/c\REACT_APP_API_BASE_URL='$REACT_APP_API_BASE_URL_STAGING deploy/.env
    - sed -i '/^REACT_APP_API_EXTERNAL_URL/c\REACT_APP_API_EXTERNAL_URL='$REACT_APP_API_EXTERNAL_URL deploy/.env
    - cat deploy/.env
    - echo "Docker pull image"
    - docker pull $CI_REGISTRY_IMAGE:$DOCKER_APP_TAG
  script:
    - echo "Deploy to staging server"
    - docker network create -d overlay lprs_front_net || true
    - docker stack deploy --with-registry-auth -c deploy/staging.yaml unicef_lprs_gu_front

deploy_prod:
  stage: deploy
  tags:
    - unicef-lprs-front
  only:
    - master
  before_script:
    - echo "Docker registry Login"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - echo "Setting env vars"
    - cp .env.example .env
    - sed -i '/^REACT_APP_API_BASE_URL/c\REACT_APP_API_BASE_URL='$REACT_APP_API_BASE_URL_PROD .env
    - cat .env
  script:
    - echo "Deploy to production server"
    - docker network create -d overlay lprs_front_net || true
    - docker stack deploy --with-registry-auth -c deploy/staging.yaml unicef_lprs_gu_front
